version: '3.9'

services:
  db:
    image: postgres:12.0
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}


  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/project
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: